"""add_description_to_model_registry

Revision ID: cac03586b99a
Revises: 1cde91f09110
Create Date: 2025-10-14 16:59:04.421025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac03586b99a'
down_revision = '1cde91f09110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_registry', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_registry', 'description')
    # ### end Alembic commands ###
